### ISSUE TITLE
[Question] Difference to 1up-lab/OneupFlysystemBundle

### ISSUE THREAD

**Issue by michaelKaefer** [thephpleague/flysystem-bundle#37]
Could someone explain to me why there are two bundles for the same cause? What is the difference to 1up-lab/OneupFlysystemBundle? Which one should we use? Sorry for posting it as an issue but I don't know where else I could ask.

The same question on the other side: https://github.com/1up-lab/OneupFlysystemBundle/issues/205

**Comment by tgalopin** [comment]
The idea behind Symfony always has been to promote good practices and maintainable architecture. In 2011, Symfony 2 was as far as I know the biggest framework introducing dependency injection at its core and it lead to a series of architectural improvements over the years. Slowly but surely, the usage of proven practices likes encapsulation and SOLID principles has been growing in PHP development.

Nowadays, I think a large chunk of PHP developers uses some kind of OOP architecture based on these principles. This is IMO one of the reason why PHP tends to be more profesionally recognized than ever before.

Now, dependency injection is great, but since Symfony 2, it always came at a price of productivity: to use dependency injection, you had to configure your services and how they depend on each other in a specific, dedicated XML or YAML configuration format. This means that *the path of least resistance was to not use dependency injection*: you could be much more efficient in the short term by not using the Symfony DI component for your app services. It's a terrible idea, but when you are a beginner, it's not that bad and you feel confortable.

To fight this, Symfony introduced autowiring in Symfony 3.3. Autowiring (and autodiscovery) relies on the good implementation of SOLID principles to automatically find and wire your classes are services usable in your application. This changed everything: now, *the path of least resistance was to use the good practices*. As a beginner, using autowiring made sense because it felt natural and efficient - even more efficient than doing everything manually in your controller.

However since the introduction of autowiring, I always had an issue with Flysystem: I wanted to have different filesystems for different usages, ie. storing my users uploads in S3 and my backups in dropbox. Because Flysystem works on a single adapter basis, I needed to either manually wire the proper filesystem in each of my services of rely on the container directly. Both are very bad ideas leading to architectural problems.

This is why Nicolas and I worked on [named autowiring aliases](https://symfony.com/doc/current/service_container/autowiring.html#dealing-with-multiple-implementations-of-the-same-type) in Symfony 4.2: a way to disinguish the proper implementation to wire based on the variable name.

As soon as this feature was released, I implemented it in my applications, and realized it could be a great bundle. I discussed it with Frank (Flysystem author) who liked the idea and I released it with his help.

I hope it answers your question.

**Comment by michaelKaefer** [comment]
Thank you for the clearification. Still I am not sure why you didn't decide to improve `1up-lab/OneupFlysystemBundle` instead. For me the negative consequence is that I have to decide between two bundles which seem to provide the exact same features :)

**Comment by tgalopin** [comment]
Also, there is another feature you may like in this bundle that's not present in the other one: lazy adapters. Basically, this means that you can switch the filesystem storage used using an environment variable.
