### ISSUE TITLE
[Question] Define/change container (rackspace or other cloud provider) at runtime ?

### ISSUE THREAD

**Issue by petitj** [thephpleague/flysystem-bundle#38]
Hi there,

i'm looking for a way to define or change the container (rackspace or any other cloud provider) at runtime. The idea is that the container should come from a database.

It seems pretty easy outside of the Symfony service autowiring context but i'd like to make this work in symfony to keep dependencies working (VichUploaderBundle).

Any hints on how to achieve this ?
Thanks

**Comment by tgalopin** [comment]
Jello,

I'm not sure what you mean by "container" but perhaps are you looking for lazy adapters? https://github.com/thephpleague/flysystem-bundle/blob/master/docs/5-using-lazy-adapter-to-switch-at-runtime.md

**Comment by petitj** [comment]
Hi, i meant Rackspace Openstack container.
I've already looked at lazy adapters but the config needs to exist first in yaml.
In my case the name of the container will come from a database.
I'm pretty new to Symfony but maybe if there's a way to set a service from a class or something...
Thanks for your input :)

**Comment by tgalopin** [comment]
Okay, I understand now. This requires a bit more work than a lazy adapter but it should be possible:

1/ VichUploaderBundle uses the `flysystem.storage` service tag to discover available storages: you can expose a custom service with this tag in order to inject it into vich_uploader behavior.

2/ VichUploaderBundle uses a lazy registry: this means that the actual instanciation of the Flysystem storage service will be delayed until you actually use it (for instance during upload).

3/ Because of 1, you can inject your own storage service, and because of 2 you can use a configurable factory to create the adapter depending on your database.

This leads me to think that it's possible to create a custom service for your adapter and use a factory for this adapter in order to configure the container to use with the database.

**Comment by petitj** [comment]
Thanks a lot ! You set me in the right direction.
I didn't have to use a custom service for VichUploaderBundle nor to tag it in the end. I just used the one i already had for Flysystem but injected the rackspace container as a static property in my controllers. It works well but doesn't feel pretty... Also, from what i understood, since a service is instantiated only once by Symfony, it means that it won't be possible to change the rackspace container once it's set.
